version: "3.8"
volumes:
  yarn_cache:
x-volumes: &default-prod-volumes
  - yarn_cache:/usr/local/share/.cache/yarn/
x-environment: &default-prod-environment
  NODE_ENV: production
  POSTGRES_HOST: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
services:
  memba-backend:
    build: ./memba-backend
    environment:
      <<: *default-prod-environment
      POSTGRES_DATABASE: membadb
    ports:
      - 3001:3000
      - 9229:9229
    volumes: *default-prod-volumes
    depends_on:
      - db
    command: ["yarn", "start:prod"]
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
